apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-service
  labels:
    app: complete-prodcution-e2e-app 
spec:
  selector:
    app: complete-prodcution-e2e-app

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30145
  type: NodePort
